#!/usr/bin/env bash
set -euo pipefail
WS="/home/kavia/workspace/code-generation/elegant-clock-223339-223348/qt_clock_native_app"
# idempotent install + probe Qt and write persistent env
PKGS=()
# refresh package lists
sudo apt-get update -qq
# ensure cmake/ctest
command -v cmake >/dev/null 2>&1 || PKGS+=(cmake)
command -v ctest >/dev/null 2>&1 || PKGS+=(cmake)
# pkg-config
command -v pkg-config >/dev/null 2>&1 || PKGS+=(pkg-config)
# dev libs
dpkg -s libglib2.0-dev >/dev/null 2>&1 || PKGS+=(libglib2.0-dev)
# Xvfb and xdpyinfo
command -v Xvfb >/dev/null 2>&1 || PKGS+=(xvfb)
command -v xdpyinfo >/dev/null 2>&1 || PKGS+=(x11-utils)
# other essentials
dpkg -s ca-certificates >/dev/null 2>&1 || PKGS+=(ca-certificates)
locale -a >/dev/null 2>&1 || PKGS+=(locales)
dpkg -s binutils >/dev/null 2>&1 || PKGS+=(binutils)
# Prefer libqt6-dev then libqt5-dev
QT_PKG=""
if dpkg -s libqt6-dev >/dev/null 2>&1; then QT_PKG=libqt6-dev
elif dpkg -s libqt5-dev >/dev/null 2>&1; then QT_PKG=libqt5-dev
fi
if [ -z "${QT_PKG}" ]; then
  if apt-cache show libqt6-dev >/dev/null 2>&1; then QT_PKG=libqt6-dev
  elif apt-cache show libqt5-dev >/dev/null 2>&1; then QT_PKG=libqt5-dev
  fi
fi
if [ -n "${QT_PKG}" ]; then PKGS+=("${QT_PKG}"); else >&2 echo "ERROR: Qt development package (libqt6-dev or libqt5-dev) not found in apt sources. Remediation: enable 'universe' (sudo add-apt-repository universe && sudo apt-get update) or add official Qt repos; aborting." && exit 10; fi
# install missing pkgs
if [ ${#PKGS[@]} -gt 0 ]; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${PKGS[@]}" >/dev/null || { >&2 echo "apt-get install failed for: ${PKGS[*]}"; exit 11; }
fi
# validate cmake >= 3.16
if ! command -v cmake >/dev/null 2>&1; then >&2 echo "cmake not installed"; exit 12; fi
CMV=$(cmake --version | head -n1 | awk '{print $3}')
# semver compare
min_ver="3.16"
ver_compare() { printf '%s
%s
' "$1" "$2" | awk -F. '{printf("%03d%03d%03d\n",($1+0),($2+0),($3+0))}' | sort -n | head -n1; }
if [ "$(ver_compare "$CMV" "$min_ver")" != "$(ver_compare "$min_ver" "$CMV")" ]; then >&2 echo "cmake version $CMV < required $min_ver"; exit 13; fi
# Probe pkg-config and filesystem for Qt pkgconfig and plugins
PKG_PATHS=()
PLUGIN_PATHS=()
for p in /usr/lib/x86_64-linux-gnu /usr/lib; do
  [ -d "$p/pkgconfig" ] && PKG_PATHS+=("$p/pkgconfig") || true
  [ -d "$p/qt6" ] && PKG_PATHS+=("$p/qt6/lib/pkgconfig" "$p/qt6/lib/x86_64-linux-gnu/pkgconfig") || true
  [ -d "$p/qt5" ] && PKG_PATHS+=("$p/qt5/lib/pkgconfig" "$p/qt5/lib/x86_64-linux-gnu/pkgconfig") || true
  [ -d "$p/qt6/plugins" ] && PLUGIN_PATHS+=("$p/qt6/plugins") || true
  [ -d "$p/qt5/plugins" ] && PLUGIN_PATHS+=("$p/qt5/plugins") || true
done
if command -v pkg-config >/dev/null 2>&1; then
  for mod in Qt6Core Qt5Core; do
    if pkg-config --exists "$mod" >/dev/null 2>&1; then
      PKG_CONFIG_PRINT_PATH=$(pkg-config --variable pc_path pkg-config 2>/dev/null || true)
      [ -n "$PKG_CONFIG_PRINT_PATH" ] && PKG_PATHS+=("$PKG_CONFIG_PRINT_PATH") || true
      break
    fi
  done
fi
# dedupe and join with :
PKG_CONFIG_FINAL=""
for x in "${PKG_PATHS[@]}"; do [[ -n "$x" && ":$PKG_CONFIG_FINAL:" != *":$x:"* ]] && PKG_CONFIG_FINAL="${PKG_CONFIG_FINAL}${x}:"; done
PKG_CONFIG_FINAL="${PKG_CONFIG_FINAL%:}"
PLUGIN_FINAL=""
for x in "${PLUGIN_PATHS[@]}"; do [[ -n "$x" && ":$PLUGIN_FINAL:" != *":$x:"* ]] && PLUGIN_FINAL="${PLUGIN_FINAL}${x}:"; done
PLUGIN_FINAL="${PLUGIN_FINAL%:}"
# Atomically write /etc/profile.d/qt_env.sh
TMPF=$(mktemp)
cat > "$TMPF" <<EOF
# Generated by automation: Qt environment helpers
export LANG=en_US.UTF-8
EOF
[ -n "$PKG_CONFIG_FINAL" ] && echo "export PKG_CONFIG_PATH=\"$PKG_CONFIG_FINAL:\\\${PKG_CONFIG_PATH-}\"" >> "$TMPF"
[ -n "$PLUGIN_FINAL" ] && echo "export QT_PLUGIN_PATH=\"$PLUGIN_FINAL:\\\${QT_PLUGIN_PATH-}\"" >> "$TMPF"
# prepend qt6 binaries if present
if [ -d "/usr/lib/x86_64-linux-gnu/qt6/bin" ]; then
  echo "export PATH=/usr/lib/x86_64-linux-gnu/qt6/bin:\$PATH" >> "$TMPF"
elif [ -d "/usr/lib/qt6/bin" ]; then
  echo "export PATH=/usr/lib/qt6/bin:\$PATH" >> "$TMPF"
fi
sudo mv "$TMPF" /etc/profile.d/qt_env.sh && sudo chmod 644 /etc/profile.d/qt_env.sh
# source now (best-effort)
. /etc/profile.d/qt_env.sh || true
# quick validation
if command -v pkg-config >/dev/null 2>&1; then
  if pkg-config --exists Qt6Core >/dev/null 2>&1; then pkg-config --modversion Qt6Core || true
  elif pkg-config --exists Qt5Core >/dev/null 2>&1; then pkg-config --modversion Qt5Core || true
  else >&2 echo "Warning: pkg-config cannot find Qt modules; runtime build may still succeed if qmake is present";
  fi
fi
# Check for common platform plugins
FOUND_PLUGIN=0
if [ -n "$PLUGIN_FINAL" ]; then
  for d in ${PLUGIN_FINAL//:/ }; do
    [ -f "$d/platforms/libqminimal.so" ] && FOUND_PLUGIN=1 && break || true
    [ -f "$d/platforms/libqoffscreen.so" ] && FOUND_PLUGIN=1 && break || true
    [ -f "$d/platforms/libqxcb.so" ] && FOUND_PLUGIN=1 && break || true
  done
fi
if [ $FOUND_PLUGIN -eq 0 ]; then >&2 echo "Warning: no Qt platform plugin detected in plugin paths; QT_QPA_PLATFORM=offscreen may fail at runtime. Install packaging that provides Qt platforms (e.g., libqt6gui6, qt6-wayland, qt6-platform-plugins or similar)"; fi
# final status
echo "OK: environment install script completed"
